### ISSUE TITLE
The permitAll matchers do not work

### ISSUE THREAD

**Issue by ShanGor** [nydiarra/springboot-jwt#6]
For the below matchers, do not work, do you have any idea to solve that?

> .antMatchers("/api-docs/**", "/actuator/**").permitAll()

**Comment by snh-png** [comment]
This issue has been fixed in the latest code. For example http://localhost:8080/health. This is because the endpoint permission must be defined in the resource server configuration instead of the main security server configuration. You can now permit all your own endpoint in the ResourceServerConfig class. Please checkout the code on Github.[https://medium.com/@nydiarra/snehashish-9166bb65e012](url)

**Comment by ShanGor** [comment]
Dear Snehasispanigrahi, thanks for reply, the link you've provided is not accessible, is it correct?

**Comment by ShanGor** [comment]
I checked the code again, saw the changes and the new code for the resource server configuration. Thanks a lot. I will try later. You are awesome!

**Comment by ShanGor** [comment]
Added the resource server configuration, it works perfectly! Thank you very much!
